name: CI/CD Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 black
      
      - name: Lint with flake8
        run: |
          flake8 src tests --max-line-length=120
      
      - name: Code formatting check with Black
        run: |
          black --check src tests
      
      - name: Run automated tests
        run: |
          pytest tests/
  
  docker-build-and-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: |
          docker build -t sentiment-analysis-app:${{ github.sha }} .
      
      - name: Push Docker Image to Registry
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker tag sentiment-analysis-app:${{ github.sha }} $DOCKERHUB_USERNAME/sentiment-analysis-app:${{ github.sha }}
          docker push $DOCKERHUB_USERNAME/sentiment-analysis-app:${{ github.sha }}

      # Add deployment steps if deploying automatically to a cloud provider.

